// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: api/proto/baseline/baseline.proto

package baseline

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BaselineService_Ping_FullMethodName = "/baseline.BaselineService/Ping"
)

// BaselineServiceClient is the client API for BaselineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BaselineService — decorative service demonstrating the gRPC + AMQP
// publish/consume pattern. Not load-bearing; used as a template for future
// extractions from the api-gateway monolith.
type BaselineServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type baselineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBaselineServiceClient(cc grpc.ClientConnInterface) BaselineServiceClient {
	return &baselineServiceClient{cc}
}

func (c *baselineServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, BaselineService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BaselineServiceServer is the server API for BaselineService service.
// All implementations must embed UnimplementedBaselineServiceServer
// for forward compatibility.
//
// BaselineService — decorative service demonstrating the gRPC + AMQP
// publish/consume pattern. Not load-bearing; used as a template for future
// extractions from the api-gateway monolith.
type BaselineServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedBaselineServiceServer()
}

// UnimplementedBaselineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBaselineServiceServer struct{}

func (UnimplementedBaselineServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedBaselineServiceServer) mustEmbedUnimplementedBaselineServiceServer() {}
func (UnimplementedBaselineServiceServer) testEmbeddedByValue()                         {}

// UnsafeBaselineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BaselineServiceServer will
// result in compilation errors.
type UnsafeBaselineServiceServer interface {
	mustEmbedUnimplementedBaselineServiceServer()
}

func RegisterBaselineServiceServer(s grpc.ServiceRegistrar, srv BaselineServiceServer) {
	// If the following call pancis, it indicates UnimplementedBaselineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BaselineService_ServiceDesc, srv)
}

func _BaselineService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaselineServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaselineService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaselineServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BaselineService_ServiceDesc is the grpc.ServiceDesc for BaselineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BaselineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "baseline.BaselineService",
	HandlerType: (*BaselineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _BaselineService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/baseline/baseline.proto",
}
